# Generated by Django 6.0 on 2025-12-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
