# Generated by Django 6.0 on 2025-12-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparations', '0002_preparation_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparation',
            name='cancelled_by_customer',
            field=models.BooleanField(default=False),
        ),
    ]
