# Generated by Django 6.0 on 2025-12-18 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('DELAYED', 'Delayed'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('delivery_address', models.TextField()),
                ('estimated_prep_time', models.PositiveIntegerField(blank=True, null=True)),
                ('delayed', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order_created', 'Order Created'), ('order_cancelled', 'Order Cancelled'), ('preparation_accepted', 'Preparation Accepted'), ('preparation_rejected', 'Preparation Rejected'), ('preparation_delayed', 'Preparation Delayed'), ('preparation_cancelled', 'Preparation Cancelled'), ('preparation_done', 'Preparation Done')], max_length=30)),
                ('source', models.CharField(choices=[('kyte_backend', 'Kyte Backend'), ('restaurant', 'Restaurant')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
